version: 0.2

phases:
  build:
    commands:
      - echo Building Docker image
      - docker build -t my-ml-app .

      - echo Running training pipeline
      - docker run \
        -e ROBOFLOW_API_KEY=$ROBOFLOW_API_KEY \
        my-ml-app